### ISSUE TITLE
楼中楼设计

### ISSUE THREAD

**Issue by oott123** [omega-bbs/spec#3]
* 是否应该设计新的数据类型表达楼中楼？
* 是否应该在查询层面区分引用和楼中楼？

**Comment by zh99998** [comment]
@oott123 > 是否应该设计新的数据类型表达楼中楼？

我觉得可以，一方面为了避免引用递归，另一方面post之后可能会由于一些奇怪的原因新增字段

**Comment by oott123** [comment]
那么，楼中楼的英文名叫啥？

**Comment by zh99998** [comment]
@oott123 Comment 如何

**Comment by cirfi** [comment]
@oott123 Subpost，姑且提议一下。

**Comment by oott123** [comment]
* 是: `Comment`
* 是: `quoted`; `comments`
